language: cpp
dist: trusty
sudo: required

install: 
  - clang++ -v
  # clang, trunk, from http://llvm.org/docs/LibFuzzer.html#id14
  - mkdir TMP_CLANG
  - cd TMP_CLANG
  - git clone https://chromium.googlesource.com/chromium/src/tools/clang
  - cd ..
  - TMP_CLANG/clang/scripts/update.py
  # Links to clang, trunk
  - ln -s ./third_party/llvm-build/Release+Asserts/bin/clang
  - ln -s ./third_party/llvm-build/Release+Asserts/bin/clang++
  # STL
  - sudo apt-get install -y libc++-dev libc++abi-dev

script:
  - clang++ -v
  - qmake
  - make
  - ./travis_qmake_clang_cpp17

